# Generated by Django 3.2.16 on 2024-05-20 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20240518_1113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='location',
            name='is_published',
        ),
    ]
